### ISSUE TITLE
Load the glove error

### ISSUE THREAD

**Issue by Haitons** [blackbbc/NER#3]
Load elmo...
Load model...
Traceback (most recent call last):
  File "/media/haiton/其他/I Like Study/github/NER/elmo_train.py", line 69, in <module>
    elmo_batcher)
  File "/media/haiton/其他/I Like Study/github/NER/model/Elmo.py", line 52, in __init__
    self._build_graph()
  File "/media/haiton/其他/I Like Study/github/NER/model/Elmo.py", line 239, in _build_graph
    self._add_embedding()
  File "/media/haiton/其他/I Like Study/github/NER/model/Elmo.py", line 68, in _add_embedding
    pretrained_vocab, pretrained_embs = load_pretrained_glove()
  File "/media/haiton/其他/I Like Study/github/NER/utils/utils.py", line 27, in load_pretrained_glove
    model = KeyedVectors.load_word2vec_format('resources/pretrained/glove/glove.6B.50d.txt')
  File "/home/haiton/anaconda3/lib/python3.5/site-packages/gensim/models/keyedvectors.py", line 1436, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/haiton/anaconda3/lib/python3.5/site-packages/gensim/models/utils_any2vec.py", line 173, in _load_word2vec_format
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
  File "/home/haiton/anaconda3/lib/python3.5/site-packages/gensim/models/utils_any2vec.py", line 173, in <genexpr>
    vocab_size, vector_size = (int(x) for x in header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: 'the'

**Comment by 2hip3ng** [comment]
我也遇到了这个问题，不知道解决了吗

**Comment by blackbbc** [comment]
这个问题我回国后看一下，现在在国外开会

**Comment by 2hip3ng** [comment]
大佬真强

**Comment by blackbbc** [comment]
https://radimrehurek.com/gensim/scripts/glove2word2vec.html
需要把glove转成word2vec格式，如果你们会的话可以自己转一下，我回国以后加个脚本

**Comment by MiskaChris** [comment]
照成这个原因的根本问题是有些glove的词向量文件是缺失第一行的，即　词表中词数　和　向量维度。
（比如40 0000 glove 的　300维词向量应该在第一行为　"400000 300"中间以空格分割）
